// agv_markers — C++17 AprilTag pose correction node
//
// Subscribes to apriltag_ros detections (apriltag_msgs format),
// estimates tag pose via solvePnP, computes robot pose in map frame
// using known marker positions, publishes correction for global EKF.
//
// Canonical marker system: AprilTag family tag36h11
// AprilTags are pose anchors and drift correctors, NOT the sole localization strategy.

#include <cmath>
#include <fstream>
#include <map>
#include <string>
#include <sstream>
#include <vector>

#include <rclcpp/rclcpp.hpp>
#include <geometry_msgs/msg/pose_with_covariance_stamped.hpp>
#include <nav_msgs/msg/odometry.hpp>
#include <sensor_msgs/msg/camera_info.hpp>
#include <std_msgs/msg/string.hpp>
#include <std_msgs/msg/empty.hpp>
#include <tf2_ros/buffer.h>
#include <tf2_ros/transform_listener.h>
#include <robot_localization/srv/set_pose.hpp>

#include <apriltag_msgs/msg/april_tag_detection_array.hpp>

#include <tf2/LinearMath/Transform.h>
#include <tf2/LinearMath/Vector3.h>
#include <tf2/LinearMath/Quaternion.h>

#include <opencv2/calib3d.hpp>
#include <opencv2/core.hpp>

struct MarkerPose {
  double x, y, z;
  double yaw;
  // Per-tag physical size in meters (Sprint E / HIGH-04-04). 0 means
  // "not declared" — fall back to the global tag_size parameter. Lets
  // floor (small) and wall (larger) tags mix in one registry without
  // corrupting the PnP geometry of one class.
  double size{0.0};
};

class MarkerCorrectionNode : public rclcpp::Node {
public:
  MarkerCorrectionNode() : Node("marker_correction") {
    declare_parameter("markers_registry_file", "");
    // Runtime registry: generated by ui_backend AprilTagManager. If present,
    // overlays/replaces the static registry. Reloaded on /markers/registry_reload.
    declare_parameter("runtime_registry_file", "");
    declare_parameter("max_detection_range", 5.0);
    declare_parameter("covariance_xy", 0.01);
    declare_parameter("covariance_yaw", 0.03);
    // Must match physical tag size. Registry uses 0.2m (20cm) tags.
    declare_parameter("tag_size", 0.2);
    declare_parameter("relocalization_threshold", 2.0);  // meters — force reset above this
    declare_parameter("min_confidence", 50.0);            // decision_margin minimum for reloc
    declare_parameter("relocalization_cooldown_ms", 500); // pause corrections after set_pose
    declare_parameter("camera_frame", std::string("zed_left_camera_frame"));
    // Set true when camera_frame names an optical-convention frame (x right,
    // y down, z forward — e.g. the ZED wrapper's zed_left_camera_optical_frame
    // or the HIL TF tree's zed_left_camera_frame_optical). When false
    // (default), camera_frame is a body-convention frame (x forward, y left,
    // z up) and the fixed optical->body rotation is applied to the solvePnP
    // tvec before the TF transform. See on_detection().
    declare_parameter("camera_frame_is_optical", false);
    declare_parameter("base_frame", std::string("base_link"));
    declare_parameter("map_frame", std::string("map"));
    declare_parameter("camera_info_topic", std::string("/zed/zed_node/left/camera_info"));
    declare_parameter("camera_info_timeout_s", 10.0);

    max_range_ = get_parameter("max_detection_range").as_double();
    cov_xy_ = get_parameter("covariance_xy").as_double();
    cov_yaw_ = get_parameter("covariance_yaw").as_double();
    tag_size_ = get_parameter("tag_size").as_double();
    reloc_threshold_ = get_parameter("relocalization_threshold").as_double();
    min_confidence_ = get_parameter("min_confidence").as_double();
    reloc_cooldown_ms_ = get_parameter("relocalization_cooldown_ms").as_int();
    camera_frame_ = get_parameter("camera_frame").as_string();
    camera_frame_is_optical_ = get_parameter("camera_frame_is_optical").as_bool();
    base_frame_ = get_parameter("base_frame").as_string();
    map_frame_ = get_parameter("map_frame").as_string();
    auto camera_info_topic = get_parameter("camera_info_topic").as_string();
    auto camera_info_timeout = get_parameter("camera_info_timeout_s").as_double();

    static_registry_path_ = get_parameter("markers_registry_file").as_string();
    runtime_registry_path_ = get_parameter("runtime_registry_file").as_string();
    reload_all_registries();

    // TF
    tf_buffer_ = std::make_shared<tf2_ros::Buffer>(get_clock());
    tf_listener_ = std::make_shared<tf2_ros::TransformListener>(*tf_buffer_);

    // Publishers
    pose_pub_ = create_publisher<geometry_msgs::msg::PoseWithCovarianceStamped>("marker_pose", 10);
    detected_pub_ = create_publisher<std_msgs::msg::String>("marker_detected", 10);
    // Raw tag IDs (whether or not in registry) — for ui_backend AprilTagManager
    raw_tag_pub_ = create_publisher<std_msgs::msg::String>("marker_raw_detected", 10);

    // Subscribers
    detection_sub_ = create_subscription<apriltag_msgs::msg::AprilTagDetectionArray>(
      "detections", 10,
      std::bind(&MarkerCorrectionNode::on_detection, this, std::placeholders::_1));

    caminfo_sub_ = create_subscription<sensor_msgs::msg::CameraInfo>(
      camera_info_topic, 10,
      [this](sensor_msgs::msg::CameraInfo::SharedPtr msg) {
        if (!has_caminfo_) {
          fx_ = msg->k[0]; fy_ = msg->k[4];
          cx_ = msg->k[2]; cy_ = msg->k[5];
          has_caminfo_ = true;
          RCLCPP_INFO(get_logger(), "Camera intrinsics: fx=%.1f fy=%.1f cx=%.1f cy=%.1f",
            fx_, fy_, cx_, cy_);
          if (caminfo_timeout_timer_) caminfo_timeout_timer_->cancel();
        }
      });

    // One-shot timer to warn if camera_info never arrives
    if (camera_info_timeout > 0.0) {
      caminfo_timeout_timer_ = create_wall_timer(
        std::chrono::duration<double>(camera_info_timeout),
        [this, camera_info_topic]() {
          if (!has_caminfo_) {
            RCLCPP_WARN(get_logger(),
              "No camera_info received after timeout on topic '%s'. "
              "AprilTag detections will be ignored until camera_info is available.",
              camera_info_topic.c_str());
          }
          caminfo_timeout_timer_->cancel();
        });
    }

    // Subscribe to global EKF output for current pose (relocalization check)
    ekf_sub_ = create_subscription<nav_msgs::msg::Odometry>(
      "odometry/global", rclcpp::SensorDataQoS(),
      [this](nav_msgs::msg::Odometry::SharedPtr msg) {
        current_ekf_x_ = msg->pose.pose.position.x;
        current_ekf_y_ = msg->pose.pose.position.y;
        has_ekf_pose_ = true;
      });

    // Iter-31: subscribe to /agv/zone/state to detect when the robot is
    // inside a rail aisle. Inside a rail, the 51 mm tube mechanically
    // constrains lateral drift to < 5 mm, so the EKF pose does NOT need
    // visual correction — and a mistimed RELOC caused by marker_correction
    // seeing adjacent-aisle / row-start tags at grazing incidence
    // poisons the ekf y (iter-28..30 c3 aborted when RELOC jogged y from
    // 2.20 to 1.90 just as rail_driver started ticking). Suppress the
    // RELOC path entirely while in_rail_aisle; keep the smooth pose
    // publication (soft correction through the EKF filter, weighted by
    // covariance) which does not trigger set_pose.
    zone_sub_ = create_subscription<std_msgs::msg::String>(
      "/agv/zone/state", 10,
      [this](std_msgs::msg::String::SharedPtr msg) {
        // Extract zone field (JSON payload); match "rail_aisle_*" prefix.
        const std::string &d = msg->data;
        const std::string needle = "\"zone\":\"";
        const auto start = d.find(needle);
        if (start == std::string::npos) return;
        const auto q_open = start + needle.size();
        const auto q_close = d.find('\"', q_open);
        if (q_close == std::string::npos) return;
        const std::string zone = d.substr(q_open, q_close - q_open);
        in_rail_aisle_ = zone.rfind("rail_aisle_", 0) == 0;
      });

    // Iter-35 (revised): also watch rail_driver's own state. When it
    // reports "driving", rail_driver has an active longitudinal goal
    // and the robot is executing rail-constrained motion. Zone feedback
    // can lag (iter-33 c5) because marker_correction pollutes the EKF
    // before zone_detector reclassifies. rail_driver_state is the
    // authoritative "rail operation in progress" signal and is immune
    // to EKF drift because rail_driver only transitions in/out of
    // "driving" on its own goal topic + tick loop.
    rail_driver_sub_ = create_subscription<std_msgs::msg::String>(
      "/agv/rail_driver/state", 10,
      [this](std_msgs::msg::String::SharedPtr msg) {
        const std::string &d = msg->data;
        const std::string needle = "\"state\":\"";
        const auto start = d.find(needle);
        if (start == std::string::npos) { rail_driver_driving_ = false; return; }
        const auto q_open = start + needle.size();
        const auto q_close = d.find('\"', q_open);
        if (q_close == std::string::npos) { rail_driver_driving_ = false; return; }
        const std::string st = d.substr(q_open, q_close - q_open);
        rail_driver_driving_ = (st == "driving");
      });

    // Service client to force-relocalize EKF when drift is catastrophic
    set_pose_client_ = create_client<robot_localization::srv::SetPose>("set_pose");

    // Hot reload trigger from ui_backend (when operator assigns/removes tags)
    auto reload_qos = rclcpp::QoS(1).transient_local().reliable();
    reload_sub_ = create_subscription<std_msgs::msg::Empty>(
      "markers/registry_reload", reload_qos,
      [this](std_msgs::msg::Empty::SharedPtr) {
        RCLCPP_INFO(get_logger(), "Reloading marker registry from disk");
        reload_all_registries();
      });

    RCLCPP_INFO(get_logger(),
      "Marker correction: %zu markers, tag_size=%.3fm, reloc_threshold=%.1fm, cooldown=%ldms",
      registry_.size(), tag_size_, reloc_threshold_, reloc_cooldown_ms_);
  }

private:
  void reload_all_registries() {
    registry_.clear();
    if (!static_registry_path_.empty()) load_registry(static_registry_path_);
    if (!runtime_registry_path_.empty()) {
      std::ifstream test(runtime_registry_path_);
      if (test.is_open()) {
        test.close();
        load_registry(runtime_registry_path_);
      }
    }
  }

  void load_registry(const std::string& path) {
    std::ifstream in(path);
    if (!in.is_open()) {
      RCLCPP_ERROR(get_logger(), "Cannot open registry: %s", path.c_str());
      return;
    }

    // Simple YAML parser for our specific format. The runtime registry is
    // rewritten by ui_backend and hot-reloaded from a subscription callback,
    // so a truncated or hand-edited line must never throw out of here —
    // malformed lines are skipped with a warning instead.
    int current_id = -1;
    MarkerPose current{0, 0, 0, 0};
    std::string line;
    // Sprint E / HIGH-04-04: commit_current validates and inserts one
    // parsed entry. Duplicate IDs keep the FIRST definition (preserves
    // the canonical entry over a random later edit); non-finite fields
    // and negative sizes drop the entry with a warning.
    auto commit_current = [&]() {
      if (current_id < 0) return;
      if (!std::isfinite(current.x) || !std::isfinite(current.y) ||
          !std::isfinite(current.z) || !std::isfinite(current.yaw) ||
          !std::isfinite(current.size) || current.size < 0.0) {
        RCLCPP_WARN(get_logger(),
          "Rejecting tag_%d from %s: non-finite field or negative size",
          current_id, path.c_str());
        return;
      }
      if (registry_.count(current_id)) {
        RCLCPP_WARN(get_logger(),
          "Duplicate tag id %d in %s — keeping the first definition",
          current_id, path.c_str());
        return;
      }
      registry_[current_id] = current;
    };
    while (std::getline(in, line)) {
      // Trim
      size_t start = line.find_first_not_of(" \t-");
      if (start == std::string::npos || line[start] == '#') continue;
      std::string trimmed = line.substr(start);

      try {
        if (trimmed.substr(0, 3) == "id:") {
          commit_current();
          current = {0, 0, 0, 0};
          // Reset BEFORE parsing: if stoi throws, fields that follow the
          // bad id line are dropped instead of overwriting a valid marker.
          current_id = -1;
          current_id = std::stoi(trimmed.substr(3));
        } else if (trimmed.substr(0, 2) == "x:") {
          current.x = std::stod(trimmed.substr(2));
        } else if (trimmed.substr(0, 2) == "y:") {
          current.y = std::stod(trimmed.substr(2));
        } else if (trimmed.substr(0, 2) == "z:") {
          current.z = std::stod(trimmed.substr(2));
        } else if (trimmed.substr(0, 4) == "yaw:") {
          current.yaw = std::stod(trimmed.substr(4));
        } else if (trimmed.substr(0, 5) == "size:") {
          // Optional per-tag physical size (HIGH-04-04). Omitted → 0 →
          // the global tag_size parameter applies at detection time.
          current.size = std::stod(trimmed.substr(5));
        }
      } catch (const std::exception& e) {
        RCLCPP_WARN(get_logger(),
          "Skipping malformed registry line in %s: '%s' (%s)",
          path.c_str(), line.c_str(), e.what());
      }
    }
    commit_current();

    RCLCPP_INFO(get_logger(), "Loaded %zu markers from %s", registry_.size(), path.c_str());
    for (auto& [id, m] : registry_) {
      RCLCPP_INFO(get_logger(), "  tag_%d: (%.2f, %.2f, %.2f) yaw=%.2f size=%.3f%s",
        id, m.x, m.y, m.z, m.yaw,
        m.size > 0.0 ? m.size : tag_size_,
        m.size > 0.0 ? "" : " (default)");
    }
  }

  void on_detection(const apriltag_msgs::msg::AprilTagDetectionArray::SharedPtr msg)
  {
    if (!has_caminfo_) return;

    // Publish raw tag IDs FIRST — before any cooldown gate or pose
    // estimation. The ui_backend AprilTagManager and rail_approach
    // service rely on this stream to know when a tag is currently
    // visible. Skipping it during relocalization cooldown silently
    // breaks the /api/apriltags/:hw/align pre-flight check (which
    // queries hasRecentDetection). 2026-04-25: fix from observed bug
    // where post-set_pose cooldown left the backend "blind" to tags
    // for 500 ms+ at a time.
    for (const auto& det : msg->detections) {
      std_msgs::msg::String raw_msg;
      raw_msg.data = "tag_" + std::to_string(det.id);
      raw_tag_pub_->publish(raw_msg);
    }

    // After set_pose, pause corrections for N EKF cycles to let the reset settle.
    // Without this, odom/cuVSLAM updates between the async call and EKF processing
    // can immediately "correct" the reset back to the drifted position.
    if (relocalization_pending_) {
      auto elapsed = (now() - reloc_request_time_).nanoseconds() / 1000000;
      if (elapsed < reloc_cooldown_ms_) {
        return;  // still in cooldown — skip pose corrections only
      }
      // Cooldown expired, resume normal operation
      relocalization_pending_ = false;
      RCLCPP_INFO(get_logger(), "Relocalization cooldown expired, resuming corrections");
    }

    // Candidate pose from each detected tag (for multi-tag voting)
    struct PoseCandidate {
      double x, y, yaw, range;
      double range_factor;
      int tag_id;
      double decision_margin;
    };
    std::vector<PoseCandidate> candidates;

    for (const auto& det : msg->detections) {
      auto it = registry_.find(det.id);
      if (it == registry_.end()) continue;

      // Estimate tag pose in camera frame using solvePnP
      // Tag corners in tag frame (centered, CCW from bottom-left).
      // Per-tag size wins over the global parameter (HIGH-04-04) so
      // floor and wall tags of different physical sizes can coexist.
      const double effective_size =
          it->second.size > 0.0 ? it->second.size : tag_size_;
      double half = effective_size / 2.0;
      std::vector<cv::Point3d> obj_pts = {
        {-half, -half, 0}, { half, -half, 0},
        { half,  half, 0}, {-half,  half, 0}
      };

      std::vector<cv::Point2d> img_pts;
      for (const auto& c : det.corners) {
        img_pts.emplace_back(c.x, c.y);
      }

      if (img_pts.size() != 4) continue;

      cv::Mat camera_matrix = (cv::Mat_<double>(3, 3) <<
        fx_, 0, cx_, 0, fy_, cy_, 0, 0, 1);
      cv::Mat dist_coeffs = cv::Mat::zeros(4, 1, CV_64F);

      cv::Vec3d rvec, tvec;
      // Iter-42 empirical benchmark: SOLVEPNP_SQPNP is the robust drop-in
      // for planar-square fiducials at grazing incidence — see
      // tools/solvepnp_noise_benchmark.py. Default SOLVEPNP_ITERATIVE
      // diverges when the TF tree reports the cam almost coplanar with
      // the tag plane (HIL bug surfaced in iter-38: 2D EKFs publish
      // base_link z=0 → cam z=0.01 → 23 M m σ on tvec.z). Same fix
      // applied in fine_servo_controller.hpp for rail_approach.
      if (!cv::solvePnP(obj_pts, img_pts, camera_matrix, dist_coeffs,
                         rvec, tvec, false, cv::SOLVEPNP_SQPNP)) {
        continue;
      }

      // Distance check
      double range = cv::norm(tvec);
      if (range > max_range_ || range < 0.1) continue;

      // Get camera→base_link transform from TF to account for camera mounting offset
      geometry_msgs::msg::TransformStamped cam_to_base_msg;
      try {
        cam_to_base_msg = tf_buffer_->lookupTransform(base_frame_, camera_frame_,
          rclcpp::Time(0, 0, RCL_ROS_TIME), rclcpp::Duration::from_seconds(0.5));
      } catch (...) { continue; }

      // Build tf2 transform from the looked-up camera→base_link
      tf2::Quaternion cam_to_base_q(
        cam_to_base_msg.transform.rotation.x,
        cam_to_base_msg.transform.rotation.y,
        cam_to_base_msg.transform.rotation.z,
        cam_to_base_msg.transform.rotation.w);
      tf2::Transform cam_to_base(cam_to_base_q, tf2::Vector3(
        cam_to_base_msg.transform.translation.x,
        cam_to_base_msg.transform.translation.y,
        cam_to_base_msg.transform.translation.z));

      const auto& marker = it->second;

      // tvec from solvePnP is in the camera OPTICAL convention (x_right,
      // y_down, z_forward). The default camera_frame (zed_left_camera_frame)
      // is a BODY-convention frame (x_forward, y_left, z_up) whose TF does
      // NOT contain the optical rotation, so convert optical -> body first:
      //   x_body = z_opt, y_body = -x_opt, z_body = -y_opt
      // (same mapping as fine_servo_controller.hpp in agv_rail_approach).
      // Then cam_to_base applies the camera mounting offset (e.g. 700mm
      // forward). With camera_frame_is_optical=true the TF already carries
      // the optical rotation and tvec is used as-is.
      const tf2::Vector3 tag_in_cam = camera_frame_is_optical_
        ? tf2::Vector3(tvec[0], tvec[1], tvec[2])
        : tf2::Vector3(tvec[2], -tvec[0], -tvec[1]);
      tf2::Vector3 tag_in_base = cam_to_base * tag_in_cam;
      double tag_fwd  = tag_in_base.x();  // forward in base_link
      double tag_left = tag_in_base.y();   // left in base_link (ROS base_link Y = left)

      // Derive robot heading from the AprilTag observation instead of odometry.
      // rvec from solvePnP gives tag orientation in camera frame. Combined with
      // the tag's known yaw in the map (marker.yaw), we get an independent heading
      // estimate that can actually correct heading drift.
      // NOTE: derived directly from rvec in the camera OPTICAL convention
      // (no TF involved); assumes the camera is mounted facing forward with
      // no yaw relative to base_link (true for the AGV's fixed ZED mount).
      cv::Mat R_ct;
      cv::Rodrigues(rvec, R_ct);
      // Extract yaw of the tag as seen in the camera frame
      // R_ct columns: tag X/Y/Z axes in camera coords (optical: X-right, Y-down, Z-forward)
      // Tag yaw in camera = atan2(R_ct[0][0], R_ct[2][0]) projected onto camera XZ plane
      double tag_yaw_in_camera = std::atan2(R_ct.at<double>(0, 0), R_ct.at<double>(2, 0));
      // Robot heading = tag's known map yaw - observed yaw in camera + PI
      // The +PI accounts for the tag facing toward the approaching robot
      double robot_yaw = marker.yaw - tag_yaw_in_camera + M_PI;
      // Normalize to [-PI, PI]
      while (robot_yaw > M_PI) robot_yaw -= 2.0 * M_PI;
      while (robot_yaw < -M_PI) robot_yaw += 2.0 * M_PI;

      // Robot position = tag position - offset rotated by robot heading
      // (tag is at known map position, robot sees it at angle relative to heading)
      double cos_yaw = std::cos(robot_yaw);
      double sin_yaw = std::sin(robot_yaw);
      double robot_x = marker.x - (tag_fwd * cos_yaw - tag_left * sin_yaw);
      double robot_y = marker.y - (tag_fwd * sin_yaw + tag_left * cos_yaw);

      double ref_range = 2.0;
      double range_factor = 1.0 + (range / ref_range) * (range / ref_range);

      candidates.push_back({robot_x, robot_y, robot_yaw, range, range_factor,
                            det.id, det.decision_margin});

      std_msgs::msg::String det_msg;
      det_msg.data = "tag_" + std::to_string(det.id);
      detected_pub_->publish(det_msg);
    }

    if (candidates.empty()) return;

    // ── Multi-tag voting: if 2+ candidates, reject outliers ──
    double final_x, final_y, final_yaw, final_range_factor;
    int best_tag_id;
    double best_decision_margin;

    if (candidates.size() >= 2) {
      // Compute median position as robust center
      std::vector<double> xs, ys;
      for (const auto& c : candidates) {
        xs.push_back(c.x);
        ys.push_back(c.y);
      }
      std::sort(xs.begin(), xs.end());
      std::sort(ys.begin(), ys.end());
      double median_x = xs[xs.size() / 2];
      double median_y = ys[ys.size() / 2];

      // Filter outliers: reject candidates > multi_tag_outlier_threshold from median
      double outlier_thresh = 1.0;  // 1.0m threshold
      std::vector<const PoseCandidate*> inliers;
      for (const auto& c : candidates) {
        double dist = std::sqrt(std::pow(c.x - median_x, 2) + std::pow(c.y - median_y, 2));
        if (dist <= outlier_thresh) {
          inliers.push_back(&c);
        } else {
          RCLCPP_WARN_THROTTLE(get_logger(), *get_clock(), 5000,
            "Tag %d rejected as outlier (%.2fm from median)", c.tag_id, dist);
        }
      }
      if (inliers.empty()) inliers.push_back(&candidates[0]);  // fallback

      // Weighted average: closer tags get more weight (1/range_factor)
      double sum_w = 0.0;
      final_x = 0.0; final_y = 0.0;
      double sum_sin = 0.0, sum_cos = 0.0;
      final_range_factor = 0.0;
      best_tag_id = inliers[0]->tag_id;
      best_decision_margin = 0.0;
      for (const auto* c : inliers) {
        double w = 1.0 / c->range_factor;
        final_x += c->x * w;
        final_y += c->y * w;
        sum_sin += std::sin(c->yaw) * w;
        sum_cos += std::cos(c->yaw) * w;
        final_range_factor += c->range_factor * w;
        if (c->decision_margin > best_decision_margin) {
          best_decision_margin = c->decision_margin;
          best_tag_id = c->tag_id;
        }
        sum_w += w;
      }
      final_x /= sum_w;
      final_y /= sum_w;
      final_yaw = std::atan2(sum_sin / sum_w, sum_cos / sum_w);
      final_range_factor /= sum_w;

      RCLCPP_INFO_THROTTLE(get_logger(), *get_clock(), 2000,
        "Multi-tag vote: %zu/%zu inliers, weighted pose (%.2f, %.2f)",
        inliers.size(), candidates.size(), final_x, final_y);
    } else {
      // Single tag — use directly (existing behavior)
      final_x = candidates[0].x;
      final_y = candidates[0].y;
      final_yaw = candidates[0].yaw;
      final_range_factor = candidates[0].range_factor;
      best_tag_id = candidates[0].tag_id;
      best_decision_margin = candidates[0].decision_margin;
    }

    // Build correction message
    geometry_msgs::msg::PoseWithCovarianceStamped correction;
    // Stamped with receipt time, not the detection stamp — switching to the
    // detection stamp changes EKF time alignment and needs runtime validation.
    correction.header.stamp = now();
    correction.header.frame_id = map_frame_;
    correction.pose.pose.position.x = final_x;
    correction.pose.pose.position.y = final_y;

    double half_yaw = final_yaw / 2.0;
    correction.pose.pose.orientation.z = std::sin(half_yaw);
    correction.pose.pose.orientation.w = std::cos(half_yaw);

    // Base covariance from covariance_xy / covariance_yaw parameters,
    // scaled quadratically with range (range_factor = 1 + (range/2)^2).
    correction.pose.covariance[0] = cov_xy_ * final_range_factor;
    correction.pose.covariance[7] = cov_xy_ * final_range_factor;
    correction.pose.covariance[35] = cov_yaw_ * final_range_factor;

    // Check if relocalization needed
    double drift = 0.0;
    if (has_ekf_pose_) {
      drift = std::sqrt(
        std::pow(final_x - current_ekf_x_, 2) +
        std::pow(final_y - current_ekf_y_, 2));
    }

    // Iter-31 gate: never RELOC while the robot is inside a rail aisle.
    // The mechanical 51 mm tube is tighter than any marker-based correction
    // and a mistimed RELOC causes the downstream rail_driver to abort on
    // a poisoned EKF pose (c3/c5 iter-28..30). Fall through to the smooth
    // publication instead so the EKF still tracks the soft correction.
    //
    // Iter-33 broadening: iter-33 c5_drive_in showed the zone-based gate
    // missing its own trigger — marker_correction RELOCed the EKF off the
    // aisle (y=-2.72 vs aisle -2.2), which made zone_detector label the
    // zone "unknown", which cleared `in_rail_aisle_`, which allowed the
    // NEXT RELOC, which poisoned the EKF further. Break the chicken-and-
    // egg by also gating on the raw EKF x-position: if the ekf says we're
    // inside a rail *section* (REAR x≤3.5 OR FRONT x≥7.5), suppress RELOC
    // regardless of y-alignment. Geometry bound from the sim USD.
    const bool ekf_in_rail_section = has_ekf_pose_ &&
        (current_ekf_x_ <= 3.5 || current_ekf_x_ >= 7.5);
    const bool reloc_allowed =
        !in_rail_aisle_ && !ekf_in_rail_section && !rail_driver_driving_;
    if (drift >= reloc_threshold_ && best_decision_margin >= min_confidence_ &&
        reloc_allowed) {
      if (set_pose_client_->service_is_ready()) {
        auto request = std::make_shared<robot_localization::srv::SetPose::Request>();
        request->pose = correction;

        relocalization_pending_ = true;
        reloc_request_time_ = now();

        auto future = set_pose_client_->async_send_request(request,
          [this, final_x, final_y, best_tag_id](
            rclcpp::Client<robot_localization::srv::SetPose>::SharedFuture result) {
            try {
              result.get();
              RCLCPP_INFO(get_logger(),
                "RELOCALIZATION SUCCESS: Tag %d, EKF reset to (%.2f, %.2f)",
                best_tag_id, final_x, final_y);
            } catch (const std::exception& e) {
              RCLCPP_ERROR(get_logger(),
                "RELOCALIZATION FAILED: Tag %d, set_pose error: %s",
                best_tag_id, e.what());
              relocalization_pending_ = false;
            }
          });

        RCLCPP_WARN(get_logger(),
          "RELOCALIZATION: Tag %d, drift=%.1fm, resetting EKF to (%.2f, %.2f)",
          best_tag_id, drift, final_x, final_y);
      }
    } else {
      pose_pub_->publish(correction);
    }

    // Iter-31: tag the log line with "suppressed_rail_aisle" when the
    // drift would have triggered a RELOC but we gated it on in_rail_aisle.
    const char *mode_str = "smooth";
    if (drift >= reloc_threshold_) {
      mode_str = reloc_allowed ? "RELOC" : "RELOC_SUPPRESSED_RAIL_AISLE";
    }
    RCLCPP_INFO_THROTTLE(get_logger(), *get_clock(), 2000,
      "Correction: %zu tags, best=%d, range_factor=%.1f, pos=(%.2f, %.2f), drift=%.1fm %s",
      candidates.size(), best_tag_id, final_range_factor, final_x, final_y, drift,
      mode_str);
  }

  // Registry
  std::map<int, MarkerPose> registry_;
  std::string static_registry_path_, runtime_registry_path_;
  double max_range_, cov_xy_, cov_yaw_, tag_size_;
  double reloc_threshold_, min_confidence_;
  int64_t reloc_cooldown_ms_;
  std::string camera_frame_, base_frame_, map_frame_;
  bool camera_frame_is_optical_{false};

  // Relocalization cooldown state
  bool relocalization_pending_{false};
  rclcpp::Time reloc_request_time_{0, 0, RCL_ROS_TIME};

  // Camera intrinsics
  bool has_caminfo_{false};
  double fx_{0}, fy_{0}, cx_{0}, cy_{0};

  // Current EKF pose (for drift detection)
  bool has_ekf_pose_{false};
  double current_ekf_x_{0}, current_ekf_y_{0};

  // Iter-31: latched from zone_detector. When true, RELOC is suppressed —
  // the rail tube owns lateral accuracy and visual corrections via
  // mis-identified tags poison the EKF instead of helping.
  bool in_rail_aisle_{false};

  // Iter-35 revised: latched from rail_driver/state. When rail_driver
  // is actively driving a longitudinal goal, the robot is executing
  // rail-constrained motion (wz=0 hard, mechanical lateral bound).
  // Suppress RELOC regardless of where zone_detector thinks we are —
  // this signal is immune to EKF drift caused by bad corrections.
  bool rail_driver_driving_{false};

  // TF
  std::shared_ptr<tf2_ros::Buffer> tf_buffer_;
  std::shared_ptr<tf2_ros::TransformListener> tf_listener_;

  // ROS
  rclcpp::Publisher<geometry_msgs::msg::PoseWithCovarianceStamped>::SharedPtr pose_pub_;
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr detected_pub_;
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr raw_tag_pub_;
  rclcpp::Subscription<apriltag_msgs::msg::AprilTagDetectionArray>::SharedPtr detection_sub_;
  rclcpp::Subscription<sensor_msgs::msg::CameraInfo>::SharedPtr caminfo_sub_;
  rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr ekf_sub_;
  rclcpp::Client<robot_localization::srv::SetPose>::SharedPtr set_pose_client_;
  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr reload_sub_;
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr zone_sub_;
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr rail_driver_sub_;
  rclcpp::TimerBase::SharedPtr caminfo_timeout_timer_;
};

int main(int argc, char** argv) {
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<MarkerCorrectionNode>());
  rclcpp::shutdown();
  return 0;
}
